version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run: java -jar /app.jar
        
      #- maven/test # checkout, build, test, and upload test results
