version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      
      build:
        steps:
      # ... steps for building/testing app ...

          - setup_remote_docker
          - maven/test # checkout, build, test, and upload test results
