version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - setup_remote_docker
      - run: mvn clean install
      - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t company/app:$CIRCLE_BRANCH .
      - run: docker push rdocker11/hello-worldapp:0.0.1
      
        
      #- maven/test # checkout, build, test, and upload test results
