version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk
    working_directory: ~/sample-springboot-api
    steps:
      - checkout
      - setup_remote_docker
          
      
      - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: mvn clean deploy -Dimage=rdocker11/hellowspringboot-api:$CIRCLE_BUILD_NUM
      
        
      #- maven/test # checkout, build, test, and upload test results
